### [CVE-2018-6552](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-6552)
![](https://img.shields.io/static/v1?label=Product&message=Apport&color=blue)
![](https://img.shields.io/static/v1?label=Version&message=n%2Fa&color=blue)
![](https://img.shields.io/static/v1?label=Vulnerability&message=Denial%20of%20service%20via%20resource%20exhaustion%2C%20privilege%20escalation%2C%20and%20escape%20from%20containers&color=brighgreen)

### Description

Apport does not properly handle crashes originating from a PID namespace allowing local users to create certain files as root which an attacker could leverage to perform a denial of service via resource exhaustion, possibly gain root privileges, or escape from containers. The is_same_ns() function returns True when /proc/<global pid>/ does not exist in order to indicate that the crash should be handled in the global namespace rather than inside of a container. However, the portion of the data/apport code that decides whether or not to forward a crash to a container does not always replace sys.argv[1] with the value stored in the host_pid variable when /proc/<global pid>/ does not exist which results in the container pid being used in the global namespace. This flaw affects versions 2.20.8-0ubuntu4 through 2.20.9-0ubuntu7, 2.20.7-0ubuntu3.7, 2.20.7-0ubuntu3.8, 2.20.1-0ubuntu2.15 through 2.20.1-0ubuntu2.17, and 2.14.1-0ubuntu3.28.

### POC

#### Reference
No PoCs from references.

#### Github
- https://github.com/Metarget/awesome-cloud-native-security

