### [CVE-2020-35917](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-35917)
![](https://img.shields.io/static/v1?label=Product&message=n%2Fa&color=blue)
![](https://img.shields.io/static/v1?label=Version&message=n%2Fa&color=blue)
![](https://img.shields.io/static/v1?label=Vulnerability&message=n%2Fa&color=brighgreen)

### Description

An issue was discovered in the pyo3 crate before 0.12.4 for Rust. There is a reference-counting error and use-after-free in From<Py<T>>.

### POC

#### Reference
No PoCs from references.

#### Github
- https://github.com/Artisan-Lab/Rust-memory-safety-bugs

