### [CVE-2021-3709](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3709)
![](https://img.shields.io/static/v1?label=Product&message=apport&color=blue)
![](https://img.shields.io/static/v1?label=Version&message=2.14.1%3C%202.14.1-0ubuntu3.29%2Besm8%20&color=brighgreen)
![](https://img.shields.io/static/v1?label=Vulnerability&message=CWE-538%20File%20and%20Directory%20Information%20Exposure&color=brighgreen)

### Description

Function check_attachment_for_errors() in file data/general-hooks/ubuntu.py could be tricked into exposing private data via a constructed crash file. This issue affects: apport 2.14.1 versions prior to 2.14.1-0ubuntu3.29+esm8; 2.20.1 versions prior to 2.20.1-0ubuntu2.30+esm2; 2.20.9 versions prior to 2.20.9-0ubuntu7.26; 2.20.11 versions prior to 2.20.11-0ubuntu27.20; 2.20.11 versions prior to 2.20.11-0ubuntu65.3;

### POC

#### Reference
- https://bugs.launchpad.net/ubuntu/+source/apport/+bug/1934308

#### Github
No PoCs found on GitHub currently.

