### [CVE-2021-32285](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-32285)
![](https://img.shields.io/static/v1?label=Product&message=n%2Fa&color=blue)
![](https://img.shields.io/static/v1?label=Version&message=n%2Fa&color=blue)
![](https://img.shields.io/static/v1?label=Vulnerability&message=n%2Fa&color=brighgreen)

### Description

An issue was discovered in gravity through 0.8.1. A NULL pointer dereference exists in the function list_iterator_next() located in gravity_core.c. It allows an attacker to cause Denial of Service.

### POC

#### Reference
- https://github.com/marcobambini/gravity/issues/319

#### Github
No PoCs found on GitHub currently.

